### PR TITLE
Add Login component

### LINKED ISSUE #4: Add 'login' component

### PR DESCRIPTION
**Pull request by JuKahl**
- 🍱 Add login icon
- 🔨 Add login button
- 🔨 Add password input
- 🔨 Add email input
- 💄 Add styling
- 🔨 Add login component

[Deployment](https://king-of-the-login-mxwvzwex23ty.herokuapp.com/storybook/index.html?path=/story/common-login--primary)

### CODE REVIEW

**Review by sweisz — COMMENTED** [review]
LGTM 💯

**Review by sweisz — COMMENTED** [review]
LGTM 💯

**Review by mrana17 — APPROVED** [review]
good structure! lgtm 🚀

**Comment by SilviaBarcellini** [comment]
all very good! 👍

**Review by RonjaMeinecke — APPROVED** [review]
well done 🦾

**Review by m-wiemers — COMMENTED** [review]
I think you could use more TypeScript to be more secure. That way you can include a button without it grumbling that an onClick is expected. Also, you can also make the label e.g. "login" variable if you specify it as a props.

**Pull request merged**
