### PR TITLE
Add 'New league' components

### LINKED ISSUE #10: Add 'overview - new league' components

### PR DESCRIPTION
**Pull request by JuKahl**
- 🔨 Add 'Create league' component
- 🔨 Add 'Join league' component
- 💄 Add styling
- Add storybook

I am aware that both 'join league' and 'create league' are practically identical as of now. However, since they will differ in their functionality, i have created them separately.

### CODE REVIEW

**Review by mhstrkmp — COMMENTED** [review]
lgtm 🚀

**Review by DNaunin — APPROVED** [review]
Good job! 🚀

**Review by RonjaMeinecke — APPROVED** [review]
🦾well done

**Review by ghost — APPROVED** [review]
LGTM 🚀

**Pull request merged**
